### PR TITLE
Add support for tags

### PR DESCRIPTION
**Pull request by cory-p-oncota**
This is a working implementation and suits my needs; let me know if you'd like for tags to follow the Record model to keep the API more consistent

### CODE REVIEW

**Comment by paulgoldbaum** [comment]
Looks good! (Ignore the failling test, that's my fault) I think that using a Map for the tags is more convenient for retrieval :+1: . One thing I would suggest is extracting the Map creation to a separate method to keep constructSeries simple. That would also make testing all branches of the switch statement less of a hassle, which you can also add if you want. Thanks!

**Comment by cory-p-oncota** [comment]
Sort of followed the pattern used by Record as it eliminates the need for casting the result to get a successful test. An outer iterable isn't required as there is only one set of tags per series. Will add coverage for the malformed response and this should be good to go.

**Comment by paulgoldbaum** [comment]
Perfect! Will cut a release right away. Thanks Cory

**Comment by cory-p-oncota** [comment]
Thank you, this library saved me a ton of time. Look forward to contributing in the future.

**Comment by paulgoldbaum** [comment]
Closes #1

**Comment by cmasekera** [comment]
@paulgoldbaum With this PR to enable group by, can still access the actual tag values? Are there any issues with exposing them? Working on something and would like to be able to associated the returned Series with the particular groupby tags. Thanks

**Comment by paulgoldbaum** [comment]
@cmasekera tags are exposed for each series object like this: result.series.head.tags("TAG_NAME"). There's currently not a way to list what tags were returned. Is this something you would need?

**Pull request merged**
