### PR TITLE
Added support for BigDecimal field

### PR DESCRIPTION
**Pull request by argyakrivos**
A simple PR adding support for BigDecimal fields.

### CODE REVIEW

**Comment by argyakrivos** [comment]
Tests seem a bit flaky:
```
- Error responses are handled correctly *** FAILED *** (32 milliseconds)
[info]   org.apache.http.conn.HttpHostConnectException: Connect to localhost:64011 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
```

AFAIAC this is good to be merged. Let me know if you want me to make further changes.

**Comment by MechanicalTyler** [comment]
Nice! This is quite useful to me.  It looks like this may pass its tests if they're just run again.  Any chance of getting this merged?

**Comment by argyakrivos** [comment]
@truppert I do not have permissions to restart the build but I don't see anything wrong with this and tests are passing locally. It looks to me that this repo might be abandoned.

**Comment by paulgoldbaum** [comment]
Hey everyone, sorry for the long wait. Changes look good but there's indeed
something wrong with the tests. I'll give it a look this week end and
release a new version

**Comment by paulgoldbaum** [comment]
@argyakrivos thanks for taking the time for the PR and sorry it took so long to merge. I will publish a release including your changes in a minute

**Pull request merged**
